name: Build & Deploy Articles

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Clone Overleaf articles manually
        run: |
          mkdir -p articles
          git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/68800ce728ec6c212c8353ee articles/hiring-systems
          # clone more if needed

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-lang-european lmodern

      - name: Convert LaTeX to HTML
        run: ./scripts/convert_articles.sh

      - name: Generate index.html
        run: ./scripts/generate_index.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
