name: Build & Deploy Articles

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Make clone script executable
        run: chmod +x ./scripts/clone_overleaf_articles.sh

      - name: Clone Overleaf articles from list
        env:
          OVERLEAF_GIT_TOKEN: ${{ secrets.OVERLEAF_GIT_TOKEN }}
        run: ./scripts/clone_overleaf_articles.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-lang-european lmodern

      - name: Make clone script executable
        run: chmod +x ./scripts/convert_articles.sh

      - name: Convert LaTeX to HTML
        run: ./scripts/convert_articles.sh

      - name: Make clone script executable
        run: chmod +x ./scripts/generate_index.sh

      - name: Generate index.html
        run: ./scripts/generate_index.sh

      - name: Copy static assets
        run: cp style.css output/style.css

      - name: Disable Jekyll
        run: touch output/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
