name: Build & Deploy Articles

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Clone Overleaf article submodules manually
        run: |
          mkdir -p articles
          git clone https://git:${{ secrets.OVERLEAF_GIT_TOKEN }}@git.overleaf.com/68800ce728ec6c212c8353ee articles/hiring-systems
          # Repeat for other articles here:
          # git clone https://git:${{ secrets.OVERLEAF_GIT_TOKEN }}@git.overleaf.com/<project-id> articles/another-article

      - name: Install dependencies (pandoc, texlive)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-lang-european lmodern

      - name: Convert LaTeX articles to HTML
        run: |
          mkdir -p output
          for d in articles/*; do
            if [ -f "$d/main.tex" ]; then
              name=$(basename "$d")
              pandoc "$d/main.tex" -s -o "output/${name}.html" --mathjax
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
