name: Sync Overleaf

on:
  push:
    paths:
      - 'articles/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        run: |
          cd articles/hiring-systems
          make
